name: Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.x
          cache: yarn
      - name: Install packages
        run: yarn install
      - name: Yarn build
        run: |
          yarn build
          zip --junk-paths artifact build/index.html
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          mv artifact.zip "evian-${TAG}.zip"
          gh release create "$TAG" "evian-${TAG}.zip" \
            --title "Release ${TAG}" \
            --notes "Changes in this Release"
